### ISSUE TITLE
How to Change AppleLogo

### ISSUE THREAD

**Issue by alexzielenski** [jatsby/ThemeFuel#1]
I noticed in your ThemeKey that you wrote you do not know how to change the apple logo under f(x). Here's a small bit of info:

The Apple logo image is stored in Assets.car in SystemAppearance.bundle. Think of SystemAppearance (and all the other *Appearance.car files) as being corollary to ArtFile.bin in the old days of theming and Assets.car in SystemAppearance akin to SArtFile.bin.

Note on the f(x): They are encoded CALayer trees which contain information on how to apply GPU-backed filters to UI elements (mostly).

**Comment by jspinella** [comment]
Thank you for the clarification!
